export const strings = {
  appTitle: 'Agent-Readiness Checker',
  runScan: 'Scan',
  runScanSelection: 'Scan selection',
  runScanNamed: 'Scan {name}',
  runScanFile: 'Scan file',
  cancelScan: 'Cancel',
  close: 'Close',
  tabOverview: 'Overview',
  tabIssues: 'Issues',
  tabAiView: 'AI view',
  tabFileContext: 'File',
  scanning: 'Scanning…',
  scanningDesign: 'Scanning your design…',
  reScan: 'Re-scan',
  scoreCaption: 'AI-readiness score',
  statusReadyFile: 'No selection — scan the file.',
  statusReadyNamedLayer: '{name} selected.',
  statusReadyOneLayer: '1 layer selected.',
  statusReadyNamedLayersMore: '{name} + {n} more selected.',
  statusReadyLayers: '{count} layers selected.',
  preScanHelp:
    'Select something on the canvas to scan it, or scan the whole file.',
  resultsHeading: 'Scan results',
  overviewPlaceholder:
    'Overview will show score, pass/issue counts, and category breakdown.',
  issuesPlaceholder:
    'Issues will list prioritized findings with why / impact / how to fix.',
  filterByCategory: 'Filter by category',
  filterAll: 'All',
  quickFixes: 'Quick fixes',
  fixAll: 'Fix all',
  totalIssues: 'Total issues',
  noIssuesFilter: 'No issues match this filter.',
  showDetails: 'Show details',
  hideDetails: 'Hide details',
  whyMatters: 'Why this matters',
  ifNotFixed: 'If you don’t fix this',
  howToFix: 'How to fix',
  fix: 'Fix',
  aiViewPlaceholder:
    'AI view will summarize how agents are likely to read this file.',
  aiViewEmptyTitle: 'Nothing selected',
  aiViewEmptyBody: 'Select one component on the canvas.',
  aiViewMultiTitle: 'Select one component',
  aiViewMultiBody: 'AI view works with one component at a time.',
  aiViewClearSelection: 'Clear selection',
  aiViewDeselect: 'Deselect',
  aiViewLocate: 'View on canvas',
  aiVariantProperties: 'Variant properties',
  aiLayout: 'Layout',
  aiValuesHeading: 'Values AI would see',
  aiDescription: 'Description',
  fileContextPlaceholder:
    'File context will show inventory and scan metadata for what was audited.',
  fileScanSection: 'Scan',
  fileUnusedVariablesSection: 'Unused variables',
  fileUnusedVariablesHint: 'Set up in this file but not used here',
  filePagesSection: 'Pages',
  fileComponentsSection: 'Components with issues',
  fileOptionalChecksSection: 'Optional checks',
  optionalLooksLikeComponent: 'Looks like a component',
  optionalHoverDisabled: 'Hover & disabled states'
} as const
