export const strings = {
  appTitle: 'Agent-Readiness Checker',
  scopeLegend: 'Scan scope',
  scopeTabSelection: 'Selection',
  scopeTabPage: 'Page',
  scopeTabFile: 'Entire file',
  scopeSelection: 'Selection / frame / component',
  scopeThisPage: 'This page',
  scopeThisPageNamed: 'This page ({name})',
  scopePages: 'Specific pages',
  scopeFile: 'Entire file',
  pagesLegend: 'Pages to include',
  runScan: 'Scan',
  runScanSelection: 'Scan selection',
  runScanNamed: 'Scan {name}',
  runScanPages: 'Scan {count} pages',
  runScanFile: 'Scan entire file',
  cancelScan: 'Cancel',
  close: 'Close',
  tabOverview: 'Overview',
  tabIssues: 'Issues',
  tabAiView: 'AI view',
  tabFileContext: 'File',
  scanning: 'Scanning…',
  scanningDesign: 'Scanning your design…',
  reScan: 'Re-scan',
  scoreCaption: 'AI-readiness score',
  statusReadyFile: 'Ready to scan the entire file.',
  statusPickPages: 'Choose one or more pages to scan.',
  statusReadyNamedPage: 'Ready to scan {name}.',
  statusReadyOnePage: 'One page selected. Ready when you are.',
  statusReadyPages: '{count} pages selected. Ready when you are.',
  statusEmptySelection:
    'Select a layer on the canvas, or scan this page / the entire file.',
  statusReadyNamedLayer: 'Ready to scan {name}.',
  statusReadyOneLayer: 'Nice — one layer selected. Ready when you are.',
  statusReadyNamedLayersMore: '{name} + {n} more. Ready when you are.',
  statusReadyLayers: '{count} layers selected. Ready when you are.',
  preScanHelp:
    'Choose what to audit, then scan. The plugin stays offline and only changes the file when you confirm a Fix.',
  resultsHeading: 'Scan results',
  overviewPlaceholder:
    'Overview will show score, pass/issue counts, and category breakdown.',
  issuesPlaceholder:
    'Issues will list prioritized findings with why / impact / how to fix.',
  filterByCategory: 'Filter by category',
  filterAll: 'All',
  quickFixes: 'Quick fixes',
  fixAll: 'Fix all',
  totalIssues: 'Total issues',
  noIssuesFilter: 'No issues match this filter.',
  showDetails: 'Show details',
  hideDetails: 'Hide details',
  whyMatters: 'Why this matters',
  ifNotFixed: 'If you don’t fix this',
  howToFix: 'How to fix',
  fix: 'Fix',
  aiViewPlaceholder:
    'AI view will summarize how agents are likely to read this file.',
  aiVariantProperties: 'Variant properties',
  aiLayout: 'Layout',
  aiValuesHeading: 'Values AI would see',
  aiDescription: 'Description',
  fileContextPlaceholder:
    'File context will show inventory and scan metadata for what was audited.',
  fileScanSection: 'Scan',
  fileUnusedVariablesSection: 'Unused variables',
  fileUnusedVariablesHint: 'Set up in this file but not used here',
  filePagesSection: 'Pages',
  fileComponentsSection: 'Components with issues',
  fileOptionalChecksSection: 'Optional checks',
  optionalLooksLikeComponent: 'Looks like a component',
  optionalHoverDisabled: 'Hover & disabled states'
} as const
